name: News Milvus
on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:
    
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: News Milvus 
        run: |
         status=$(curl -o /dev/null -s -w "%{http_code}" -m 600 ${{ secrets.URL }})
         echo "Status code: $status"
         if [ "$status" -ne 200 ]; then
           echo "URL returned status code other than 200"
           exit 1
         fi
