name: News Milvus
on:
  schedule:
    - cron: '*/20 * * * *'  # Runs every 20 minutes
  workflow_dispatch:
    
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: News Milvus 
        run: curl -m 600 ${{ secrets.URL }}
